version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/
permissions:
  - object: /var/www/html/scripts/deploy.sh
    pattern: "*"
    mode: "+x"
    owner: root
    group: root
    type:
      - file
hooks:
  AfterInstall:
    - location: scripts/deploy.sh
      timeout: 300
      runas: root